server:
  port: 8080
  servlet:
    context-path: /api


spring:
  main:
    allow-circular-references: true

  application:
    name: library-management

  jackson:
    time-zone: Asia/Bangkok

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.jvpibpaxrdubqxizjiik
    password: congnghephanmem@1234
    driver-class-name: org.postgresql.Driver
  jpa:
   hibernate:
     ddl-auto: none
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       default_schema: public

jwt:
  signerKey: "60M5CCxTcS4Hm6qLkNCcGvP1WmZ0ffbmDCIdyDDNkVL32fvZSndndfM5vWfSgEgk"
  valid-duration: 30 # in second
  refreshable-duration: 36000 # in seconds

debug: true
