server:
  port: 8080
  servlet:
    context-path: /api


spring:
  application:
    name: library-management

  jackson:
    time-zone: Asia/Bangkok

  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.jvpibpaxrdubqxizjiik
    password: congnghephanmem@1234
    driver-class-name: org.postgresql.Driver
  jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
   properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
       default_schema: public

jwt:
  signerKey: "60M5CCxTcS4Hm6qLkNCcGvP1WmZ0ffbmDCIdyDDNkVL32fvZSndndfM5vWfSgEgk"

debug: true
